---
title: "Case Study II"
output:
 bookdown::html_document2:
      toc: true
      toc_float: true
      number_sections: true
---

```{r, echo=FALSE,message=FALSE}
rm(list=ls(all=TRUE))  # removes all objects from the current workspace

library(LongCART)
library(ggplot2)
library(plotly)#used for plotting
library(kableExtra)
library(reshape2)
library(survey)
library(tableone)
library(labelled)

data("ACTG175")
```

# Estimated Value Functions
```{r,echo=FALSE}
group1=c(2)
group2=c(1)
formula="z~karnof+race+gender+symptom+str2+cd4.0+wtkg"


ACTG175_wide=reshape(ACTG175,idvar = c("pidnum"), timevar = "time", direction = "wide", v.names=c("cd4"))
ACTG175_wide=ACTG175_wide%>%filter(arms%in%c(group1,group2))
ACTG175_wide$z=(ACTG175_wide$arms==2)+0
```

## Estimated Value Function Using Normalized IPW
```{r,echo=FALSE,fig.cap="Estimated value of regime using normalized IPW"}
source("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/Common_Functions.R")
sequence1=seq(50,100,5)
sequence2=seq(200,600,10)
theta=as.matrix(expand.grid(sequence1,sequence2))
colnames(theta)=c("Weight","Baseline_CD4")

proba=compute_probas(formula=formula,Dati=ACTG175_wide,group1=group1,group2=group2,bayes=FALSE,dirichi=NA)
predictions=apply(theta,1,FUN=checki_compliant2d,Dati=ACTG175_wide,group1=group1,group2=group2,weight_estimate=TRUE,proba=proba,normalize=TRUE)

# Surface plot of estimated value function
data_grid2=data.frame(cd4_20week=predictions,
                      weight=theta[,1],
                      cd4_baseline=theta[,2])
plot_matrix2 <- t(acast(data_grid2, weight~ cd4_baseline, value.var="cd4_20week"))


plot_ly(
  x = as.numeric(colnames(plot_matrix2)), 
  y = as.numeric(rownames(plot_matrix2)), 
  z = plot_matrix2) %>% 
  add_surface(opacity=0.8) %>%
  layout(
    scene = list(
      xaxis = list(title = "Weight (Kg)",range=c(50,100)),
      yaxis = list(title = "Baseline CD4", range=c(200,600)),
      zaxis = list(title = "20 Week CD4",range=c(371,410)),
      camera = list(eye = list(x = 1.95, y = -1.25, z = 1.25))
    ))%>%add_trace(x=ACTG175_wide$wtkg, y=ACTG175_wide$cd4.0, z=rep(372,nrow(ACTG175_wide)), type="scatter3d", mode="markers",marker = list(size = 2,opacity=0.8,color="darkblue"))

#Contour plot
# fig=plot_ly(x=~theta[,1],
#             y=~theta[,2],
#             z=~predictions, type="contour",
#             colorscale="Greys",line=list(color="black"),contours = list(showlabels = TRUE))
# fig%>%colorbar(title = "20 Week CD4",titlefont=list(size=25),tickfont=list(size=15))%>%
#   layout(xaxis = list(title = "Baseline Weight (kg)",titlefont=list(size=25),tickfont=list(size=15)),
#          yaxis = list(title = "Baseline CD4",titlefont=list(size=25),tickfont=list(size=15)))
```


## Interpolating GP with Normalized IPW

```{r,echo=FALSE,fig.cap="Estimated value of regime using interpolating GP after an additional 25 sampled points"}
theta=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/theta_21TRUETRUE.csv")
xhist=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/xhist_21TRUeTRUE.csv")
yhist=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/yhist_21TRUETRUE.csv")
Final_Data=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/Final_Data_21TRUETRUE.csv")


data_grid2=data.frame(cd4_20week=Final_Data$z[Final_Data$groupy==1],
                      weight=Final_Data$x[Final_Data$groupy==1],
                      cd4_baseline=Final_Data$y[Final_Data$groupy==1])
plot_matrix2 <- t(acast(data_grid2, weight~ cd4_baseline, value.var="cd4_20week"))


plot_ly(
  x = as.numeric(colnames(plot_matrix2)), 
  y = as.numeric(rownames(plot_matrix2)), 
  z = plot_matrix2) %>% 
  add_surface(opacity=0.8)%>%
  layout( scene=list(xaxis = list(title="Baseline Weight (kg)"),
                    yaxis = list(title="Baseline CD4"),
                    zaxis =  list(title="20 Week CD4"))) %>%
  add_trace(x=Final_Data$x[Final_Data$groupy==2], y=Final_Data$y[Final_Data$groupy==2],                  z=Final_Data$z[Final_Data$groupy==2],type="scatter3d", mode="markers",marker = list(size = 2,opacity=0.8,color="darkblue",size=10))



#Contour Plot
# data_grid2=data.frame(cd4_20week=Final_Data$z[Final_Data$groupy==1],
#                       weight=Final_Data$x[Final_Data$groupy==1],
#                       cd4_baseline=Final_Data$y[Final_Data$groupy==1])
# plot_matrix2 <- t(acast(data_grid2, weight~ cd4_baseline, value.var="cd4_20week"))

# fig=plot_ly(x=~Final_Data$x[Final_Data$groupy==1],
#             y=~Final_Data$y[Final_Data$groupy==1],
#             z=~Final_Data$z[Final_Data$groupy==1], type="contour",
#             colorscale="Greys",line=list(color="black"), contours = list(showlabels = TRUE))
# fig%>%colorbar(title = "20 Week \n CD4",titlefont=list(size=25),tickfont=list(size=15))%>%
#   layout(
#          xaxis = list(title = "Baseline Weight (kg)",titlefont=list(size=25),tickfont=list(size=15)),
#          yaxis = list(title = "Baseline CD4",titlefont=list(size=25),tickfont=list(size=15)))%>%
#   add_trace(x=~Final_Data$x[Final_Data$groupy==2],y=~Final_Data$y[Final_Data$groupy==2],
#             type = "scatter", mode="markers", marker=list(color="grey"),inherit=FALSE)


```

## Homoskedastic GP with Normalized IPW

```{r, echo=FALSE,fig.cap="Estimated value of regime using homoskedastic GP after an additional 25 sampled points"}
theta=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/theta_Homo_21TRUETRUE.csv")
xhist=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/xhist_Homo_21TRUETRUE.csv")
yhist=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/yhist_Homo_21TRUETRUE.csv")
Final_Data=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/Final_Data_Homo_21TRUETRUE.csv")


data_grid2=data.frame(cd4_20week=Final_Data$z[Final_Data$groupy==1],
                      weight=Final_Data$x[Final_Data$groupy==1],
                      cd4_baseline=Final_Data$y[Final_Data$groupy==1])
plot_matrix2 <- t(acast(data_grid2, weight~ cd4_baseline, value.var="cd4_20week"))


plot_ly(
  x = as.numeric(colnames(plot_matrix2)), 
  y = as.numeric(rownames(plot_matrix2)), 
  z = plot_matrix2) %>% 
  add_surface(opacity=0.8)%>%
  layout(
         scene=list(xaxis = list(title="Baseline Weight (kg)"),
                    yaxis = list(title="Baseline CD4"),
                    zaxis =  list(title="20 Week CD4"))) %>%
  add_trace(x=Final_Data$x[Final_Data$groupy==2], y=Final_Data$y[Final_Data$groupy==2],                  z=Final_Data$z[Final_Data$groupy==2],type="scatter3d", mode="markers",marker = list(size = 2,opacity=0.8,color="darkblue",size=10))



#Contour Plot
# data_grid2=data.frame(cd4_20week=Final_Data$z[Final_Data$groupy==1],
#                       weight=Final_Data$x[Final_Data$groupy==1],
#                       cd4_baseline=Final_Data$y[Final_Data$groupy==1])
# plot_matrix2 <- t(acast(data_grid2, weight~ cd4_baseline, value.var="cd4_20week"))


# fig=plot_ly(x=~Final_Data$x[Final_Data$groupy==1],
#             y=~Final_Data$y[Final_Data$groupy==1],
#             z=~Final_Data$z[Final_Data$groupy==1], type="contour",
#             colorscale="Greys",line=list(color="black"), contours = list(showlabels = TRUE))
# fig%>%colorbar(title = "20 Week \n CD4",titlefont=list(size=25),tickfont=list(size=15))%>%
#   layout(xaxis = list(title = "Baseline Weight (kg)",titlefont=list(size=25),tickfont=list(size=15)),
#          yaxis = list(title = "Baseline CD4",titlefont=list(size=25),tickfont=list(size=15)))%>%
#   add_trace(x=~Final_Data$x[Final_Data$groupy==2],y=~Final_Data$y[Final_Data$groupy==2],
#             type = "scatter", mode="markers", marker=list(color="grey"),inherit=FALSE)

```


## Heteroskedstic GP Normalized IPW

```{r,echo=FALSE,fig.cap="Estimated value of regime using heteroskedastic GP after an additional 25 sampled points"}
theta=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/theta_Hetero_21TRUETRUE.csv")
xhist=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/xhist_Hetero_21TRUETRUE.csv")
yhist=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/yhist_Hetero_21TRUETRUE.csv")
Final_Data=read.csv("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Analysis/21_WeightTrue/Final_Data_Hetero_21TRUETRUE.csv")


data_grid2=data.frame(cd4_20week=Final_Data$z[Final_Data$groupy==1],
                      weight=Final_Data$x[Final_Data$groupy==1],
                      cd4_baseline=Final_Data$y[Final_Data$groupy==1])
plot_matrix2 <- t(acast(data_grid2, weight~ cd4_baseline, value.var="cd4_20week",marker = list(size = 2,opacity=0.8,color="darkblue",size=10)))


plot_ly(
  x = as.numeric(colnames(plot_matrix2)), 
  y = as.numeric(rownames(plot_matrix2)), 
  z = plot_matrix2) %>% 
  add_surface(opacity=0.8)%>%
  layout(
         scene=list(xaxis = list(title="Baseline Weight (kg)"),
                    yaxis = list(title="Baseline CD4"),
                    zaxis =  list(title="20 Week CD4"))) %>%
  add_trace(x=Final_Data$x[Final_Data$groupy==2], y=Final_Data$y[Final_Data$groupy==2],                  z=Final_Data$z[Final_Data$groupy==2],type="scatter3d", mode="markers",marker = list(size = 2,opacity=0.8,color="darkblue",size=10))

# Contour Plot
# fig=plot_ly(x=~Final_Data$x[Final_Data$groupy==1],
#             y=~Final_Data$y[Final_Data$groupy==1],
#             z=~Final_Data$z[Final_Data$groupy==1], type="contour",
#             colorscale="Greys",line=list(color="black"), contours = list(showlabels = TRUE))
# fig%>%colorbar(title = "20 Week \n CD4",titlefont=list(size=25),tickfont=list(size=15))%>%
#   layout(
#          xaxis = list(title = "Baseline Weight (kg)",titlefont=list(size=25),tickfont=list(size=15)),
#          yaxis = list(title = "Baseline CD4",titlefont=list(size=25),tickfont=list(size=15)))%>%
#   add_trace(x=~Final_Data$x[Final_Data$groupy==2],y=~Final_Data$y[Final_Data$groupy==2],
#             type = "scatter", mode="markers", marker=list(color="grey"),inherit=FALSE)
```




